POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{
   "_id": "",
   "name": {
      "first": "Bulgan",
      "last": "Galbadrakh"
   },
   "email": "bgalbadrakh@mum.edu",
   "password": "pass123",
   "specialty": [{"id": 1, 
      "name": "Backend developer",
      "description": "Design and develop server side web applications"},
      {"id": 2, 
         "name": "Frontend developer",
         "description": "Design and develop client side web applications"}],
   "hour_rate": 45,
   "phone_number": "4259195555",
   "experience": 2,
   "address": {
      "location": {
         "type": "Point",
         "coordinates": [-91.9696223, 41.0236518]
      },
      "street": "5900 119th Ave. SE",
      "state": "WA",
      "city": "Bellevue",
      "zip_code": "98006"
   },
   "description": "Software Developer with 6 years of professional experience developing full-stack web applications and with strong knowledge of Java",
   "photo": ""
}
